---

apiVersion: v1
kind: Service
metadata:
  name: redis-headless-service
  namespace: microshop
spec:
  type: ClusterIP
  selector:
    app: redis-headless
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis