---

apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: microshop
data:
  database_name: "products"
  redis_host: "redis-headless-service"
  log_level: "info"
  cache_ttl: "3600"